insert into dashboards (dashboard_reference_name) values ('tranquilo.neto@gmail.com');
insert into users (forename, surname, user_master, email, password, role, dashboard_id, active) values ('Tranquilo', 'Dognini Neto', null, 'tranquilo.neto@gmail.com', '6yXLHUUvCZsOe5OkmwSSHw==', 'ADMIN', 1, 1);
insert into dashboards (dashboard_reference_name) values ('soraia.dognini@gmail.com');
insert into users (forename, surname, user_master, email, password, role, dashboard_id, active) values ('Soraia', 'Soares Dognini', 1, 'soraia.dognini@gmail.com', 'TRB6JqEHH0JA8luy3rJdcg==', 'USER', 2, 1);
insert into menus (label_en_gb, label_pt_br, menu_type, menu_group, link, url, murl, position, role, active) values ('Home', 'Home', 'G', null, 1, '/pages/home.faces', '/m/mhome.faces', '00', 'USER', 1);
insert into menus (label_en_gb, label_pt_br, menu_type, menu_group, link, url, murl, position, role, active) values ('Admin', 'Admin', 'G', null, 0, null, null, '10', 'ADMIN', 1);
insert into menus (label_en_gb, label_pt_br, menu_type, menu_group, link, url, murl, position, role, active) values ('Menus', 'Menus', 'I', 2, 1, '/pages/menu/list.faces', '/m/menu/mlist.faces', null, 'ADMIN', 1);
insert into menus (label_en_gb, label_pt_br, menu_type, menu_group, link, url, murl, position, role, active) values ('Users', 'Usuários', 'I', 2, 1, '/pages/user/list.faces', '/m/user/mlist.faces', null, 'ADMIN', 1);
insert into menus (label_en_gb, label_pt_br, menu_type, menu_group, link, url, murl, position, role, active) values ('Categories', 'Categorias', 'G', null, 1, '/pages/category/list.faces', '/m/category/mlist.faces', '20', 'USER', 1);
insert into menus (label_en_gb, label_pt_br, menu_type, menu_group, link, url, murl, position, role, active) values ('Payees', 'Credores', 'G', null, 1, '/pages/payee/list.faces', '/m/payee/mlist.faces', '30', 'USER', 0);
insert into menus (label_en_gb, label_pt_br, menu_type, menu_group, link, url, murl, position, role, active) values ('Transactions', 'Transações', 'G', null, 1, '/pages/transaction/list.faces', '/m/transaction/mlist.faces', '40', 'USER', 1);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('R', 'Wage Neto', 'Salário Neto', 'Wage Neto', 1, 1);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('R', 'Wage Soraia', 'Salário Soraia', 'Wage Soraia', 1, 1);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Housing Letting', 'Moradia Aluguel', 'Letting', 1, 1);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Housing Furniture and Other Expenses', 'Moradia Decoração e outras Despesas', 'Housing Other Expenses', 1, 1);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Supermarket', 'Supermercado', 'Supermarket', 1, 1);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Food Snacks', 'Comida Lanches', 'Snacks', 1, 1);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Food Meals', 'Comida Refeições', 'Meals', 1, 1);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Transport Oyster Card', 'Transporte Oyster Card', 'Oyster Card', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Transport Contactless', 'Transporte Contactless', 'Contactless', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Transport Petrol', 'Transporte Combustível', 'Petrol', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Leisure Travels', 'Lazer Viagens', 'Travels', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Leisure Meals', 'Lazer Refeições', 'Meals', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Leisure Tickets and Others', 'Lazer Ingressos e Outros', 'Tickets and Others', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Gifts', 'Presentes', 'Gifts', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Scrapbooking', 'Scrapbook', 'Scrapbooking', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Pharmacy and Medicine', 'Farmácia e Remédios', 'Pharmacy and Medicine', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Clothes, Shoes and Accessories', 'Roupas, Calçados e Acessórios', 'Clothes, Shoes and Accessories', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Courses', 'Cursos', 'Courses', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Contributions Tithes', 'Contribuições Dízimos', 'Tithes', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Contributions Firstfruits', 'Contribuições Primícias', 'Firstfruits', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Contributions Offerings', 'Contribuições Ofertas', 'Offerings', 1, 2);
insert into categories (category_type, name_en_gb, name_pt_br, description, active, user_id) values ('E', 'Acquisitions', 'Aquisições', 'Acquisitions', 1, 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-23', 'E', 5, 'S', 1.47, 'Compra Tesco Express', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-30', 'E', 5, 'S', 1, 'Compra Tesco Express', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-31', 'E', 5, 'S', 3.12, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-25', 'E', 5, 'S', 2.7, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-06', 'E', 5, 'S', 6.61, 'Compra Lidl', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-16', 'E', 5, 'S', 1, 'Compra Poundland - pÃ£o', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-16', 'E', 5, 'S', 1.7, 'Compra Lidl', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-19', 'E', 5, 'S', 5.55, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-14', 'E', 5, 'S', 0.5, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-07', 'E', 5, 'S', 4.59, 'Compra Lidl', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-01', 'E', 5, 'S', 0.3, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-05', 'E', 5, 'S', 3.97, 'Compra Tesco Express', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-29', 'E', 5, 'S', 2.33, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-09', 'E', 5, 'S', 3.74, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-05', 'E', 5, 'S', 9.21, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-10', 'E', 5, 'S', 8.37, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-04', 'E', 5, 'S', 0.75, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-12', 'E', 5, 'S', 7.64, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-12', 'E', 5, 'S', 2.69, 'Compra TESCO Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-10', 'E', 5, 'S', 2.4, 'Compra Tesco Express', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-09', 'E', 5, 'S', 6.46, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-12', 'E', 5, 'S', 0.46, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-12', 'E', 5, 'S', 3.96, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-30', 'E', 5, 'S', 5.93, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-26', 'E', 5, 'S', 3.93, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-07', 'E', 5, 'S', 4.19, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-01', 'E', 5, 'S', 2.02, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-23', 'E', 5, 'S', 3.79, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-04', 'E', 5, 'S', 1.61, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-10-06', 'E', 5, 'S', 0.49, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-04', 'E', 5, 'S', 1, 'Compra Tesco Express', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-03', 'E', 5, 'S', 0.7, 'Compra SainsburyÂ´s', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-23', 'E', 12, 'S', 6.1, 'Lanche no Costa Coffee', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-27', 'E', 12, 'S', 11.45, 'Lanche Pret A Manger', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-11', 'E', 12, 'S', 4.8, 'AlmoÃ§o IKEA', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-07', 'E', 12, 'S', 0.99, 'MC Donalds', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-07', 'E', 12, 'S', 2.29, 'Lanche Mc', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-09', 'E', 12, 'S', 0.6, 'Compra Ikea', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-31', 'E', 5, 'S', 0.8, 'Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-29', 'E', 5, 'S', 1, 'Compra batom na "1 Pound".', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-14', 'E', 5, 'S', 1.69, 'Compra Boots (Condicionador)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-19', 'E', 5, 'S', 2, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-12', 'E', 5, 'S', 0.7, 'Compra TESCO Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-07', 'E', 5, 'S', 0.22, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-31', 'E', 5, 'S', 1, 'Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-12', 'E', 5, 'S', 1.66, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-29', 'E', 15, 'S', 3.05, 'Compra na "The Works".', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-29', 'E', 15, 'S', 1, 'Compra na "Tiger".', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-16', 'E', 15, 'S', 1.25, 'Compra Wilko (carimbo)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-16', 'E', 15, 'S', 1, 'Compra Poundland', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-16', 'E', 15, 'S', 2.05, 'Compra Poundland', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-16', 'E', 15, 'S', 0.99, 'Compra SAM 99P', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-15', 'E', 15, 'S', 1.5, 'Compra Ryman', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-19', 'E', 15, 'S', 0.3, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-14', 'E', 15, 'S', 0.5, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-05', 'E', 15, 'S', 1.29, 'Compra LIDL', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-06', 'E', 16, 'S', 0.75, 'Vitamina C', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-19', 'E', 16, 'S', 0.25, 'Compra Tesco Extra', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-07', 'E', 16, 'S', 0.65, 'Compra LIDL (vitamina)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-12', 'E', 16, 'S', 0.65, 'Compra LIDL (vitamina D)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-23', 'E', 16, 'S', 0.75, 'Vitamina C', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-16', 'E', 17, 'S', 11.5, 'Compra PRIMARK (lingirie e pijama)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-16', 'E', 17, 'S', 4, 'Compra PRIMARK (Lingirie)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-20', 'E', 4, 'S', 1, 'Compra Ikea', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-11', 'E', 4, 'S', 0.5, 'Compra IKEA', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-01-12', 'E', 4, 'S', 0.5, 'Compra IKEA', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-07', 'E', 4, 'S', 2.4, 'Compra IKEA', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-11-04', 'E', 4, 'S', 0.7, 'Compra IKEA', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-02-14', 'E', 14, 'S', 5.5, 'Compra presente para Neto (ValentineÂ´s Day)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2015-12-17', 'E', 14, 'S', 13, 'Presente Albano', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-10', 'E', 19, 'S', 45, 'DÃ­zimo (Neto)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-09', 'E', 21, 'S', 1.7, 'Oferta (Soraia)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-12', 'E', 3, 'W', 180, 'Pgto Aluguel BG = Â£190-Â£10 (Limpeza casa - 2 semana)', 2);
insert into transactions (transaction_date, category_type, category, record_type, value, history, user) values ('2016-03-05', 'E', 3, 'W', 180, 'Pgto Aluguel BG = Â£190-Â£10 (Limpeza casa - 1 semana)', 2);
